controllers:
    resource: ../src/Controller/
    type: attribute

app_luckey_number:
    path : /luckey/number
    controller : App\Controller\LuckeyController::number


app_add:
    path : /add
    controller : App\Controller\AddController::index