<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ncy6r3\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ncy6r3/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container0ncy6r3.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container0ncy6r3\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container0ncy6r3\App_KernelTestDebugContainer([
    'container.build_hash' => '0ncy6r3',
    'container.build_id' => '8b9d29ca',
    'container.build_time' => 1653690171,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0ncy6r3');
