<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_add' => [[], ['_controller' => 'App\\Controller\\AddController::index'], [], [['text', '/add']], [], [], []],
    'app_luckey_number' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/luckey/number']], [], [], []],
];
